export const SET_BUDGET = 'SET_BUDGET';
export const GET_BUDGET = 'GET_BUDGET';

export const GET_DAY = 'GET_DAY';

export const ADDING_PURCHASES_SWITCH = "ADDING_PURCHASES_SWITCH";
export const ADDED_PURCHASE = "ADDED_PURCHASE";