export const SET_BUDGET = 'SET_BUDGET';
export const GET_BUDGET = 'GET_BUDGET';

export const GET_DAY = 'GET_DAY';
export const SET_DAY = "SET_DAY";
export const SET_PAGE = "SET_PAGE";
export const SET_DAY_FOR_PURCHASES = "SET_DAY_FOR_PURCHASES";

export const ADDING_PURCHASES_SWITCH = "ADDING_PURCHASES_SWITCH";
export const ADDING_PURCHASES_SWITCH_DISABLE = "ADDING_PURCHASES_SWITCH_DISABLE";
export const ADDED_PURCHASE = "ADDED_PURCHASE";

export const SET_WEEK = "SET_WEEK";